name: basic_env
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - pandas
  - scikit-learn
  - numba
  - statsmodels
  - pip
  - pip:
    - geostatspy
